version: "3.7"

services:
  php:
    container_name: piwowar-php
    working_dir: /application
    image: php:7.4.6-fpm-alpine
    volumes:
      - .:/application

  composer:
    image: composer:2.0
    working_dir: /application
    command: composer build
    volumes:
      - .:/application